=== navvvs/CAT2_WD/Validation/form.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="CHRIST">
<xs:complexType>
<xs:sequence>
<xs:element name="COMPUTER-SCIENCE" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="STU-NAME" type="xs:string"></xs:element>
<xs:element name="STU-UNIVERSITY" type="xs:string"></xs:element>
<xs:element name="STU-PHONE" type="xs:integer"></xs:element>
<xs:element name="STU-EMAIL" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

=== navvvs/CAT2_WD/Validation/form.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="form.xsl"?>
<CHRIST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="form.xsd">
  <COMPUTER-SCIENCE>
    <STU-NAME>Navin</STU-NAME>
    <STU-UNIVERSITY>Christ university</STU-UNIVERSITY>
    <STU-PHONE>7592818429</STU-PHONE>
    <STU-EMAIL>navinknaresh@christuniversity.in</STU-EMAIL>
  </COMPUTER-SCIENCE>
  <COMPUTER-SCIENCE>
    <STU-NAME>Bubloo</STU-NAME>
    <STU-UNIVERSITY>Christ university</STU-UNIVERSITY>
    <STU-PHONE>7592776429</STU-PHONE>
    <STU-EMAIL>bubbbs@christuniversity.in</STU-EMAIL>
  </COMPUTER-SCIENCE>
  <COMPUTER-SCIENCE>
    <STU-NAME>Ankitha</STU-NAME>
    <STU-UNIVERSITY>Christ university</STU-UNIVERSITY>
    <STU-PHONE>9987454637</STU-PHONE>
    <STU-EMAIL>ankuuuuu@christuniversity.in</STU-EMAIL>
  </COMPUTER-SCIENCE>
</CHRIST>
